version: '3.8'

services:

  kafka:
    image: confluentinc/cp-kafka:7.4.1   # Kafka with KRaft support
    container_name: kafka
    ports:
      - "9092:9092"   # client access

    environment:

      # 🔹 Unique node ID
      KAFKA_NODE_ID: 1

      # 🔹 Roles (no ZooKeeper needed)
      KAFKA_PROCESS_ROLES: broker,controller

      # 🔹 Listeners (client + controller)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # 🔹 Client connection address
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # 🔹 Protocol mapping
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # 🔹 Controller listener
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 🔹 Controller quorum (single node)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # 🔹 Storage
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      # 🔹 Cluster ID (generate once)
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # 🔹 Internal topic configs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # 🔹 Default partitions
      KAFKA_NUM_PARTITIONS: 3


  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]


  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis


#  mysql:
#    image: mysql:8.0
#    container_name: paypal
#    restart: always
#
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: paypal-db
#      MYSQL_USER: paypal-db
#      MYSQL_PASSWORD: paypal-db
#
#    ports:
#      - "3306:3306"
#
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      retries: 5


volumes:
  mysql_data: