spring:
  application:
    name: configurationService
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/Config

server:
  port: 8888