spring.application.name=Video


# spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
# spring.datasource.username=your_username
# spring.datasource.password=your_password
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA / Hibernate settings
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update   # (create, update, validate, none)
# spring.jpa.show-sql=true

# Maximu file size allowed for a singlefile upload
spring.servlet.multipart.max-file-size=1000MB
# Maximu number of files allowed for a single upload multipart/form-data
spring.servlet.multipart.max-request-size=1000MB

files.video =video/