spring:
  application:
    name: aiService
  data:
    mongodb:
      uri: mongodb+srv://e%2Dshop:e%2Dshop@microservice-freelence.f8tew3n.mongodb.net/AiFitnessRecommedation?retryWrites=true&w=majority


server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/