spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile
          github:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

  mongodb:
    uri: mongodb://admin:admin123@localhost:27017/mydatabase?authSource=admin
    auto-index-creation: true

  logging:
    level:
      org.springframework.data.mongodb:
        core.MongoTemplate: DEBUG

server:
  port: 8181
